name: spectrace
channels:
  - conda-forge
  - defaults
dependencies:
  - libopenvino-auto-plugin=2025.2.0=hed573e4_1
  - libdeflate=1.25=h17f619e_0
  - libvpl=2.15.0=h54a6638_1
  - numba=0.62.1=py311h6220fa4_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - libxslt=1.1.43=h711ed8c_1
  - setuptools=80.9.0=pyhff2d567_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - decorator=5.2.1=pyhd8ed1ab_0
  - libllvm21=21.1.5=hf7376ad_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - lame=3.100=h166bdaf_1003
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - scipy=1.16.3=py311h1e13796_0
  - libopus=1.5.2=hd0c01bc_0
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgettextpo-devel=0.25.1=h3f43e3d_1
  - libunwind=1.8.3=h65a8314_0
  - libclang-cpp21.1=21.1.5=default_h99862b1_1
  - libdrm=2.4.125=hb03c661_1
  - libntlm=1.8=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - harfbuzz=12.2.0=h15599e2_0
  - libbrotlienc=1.2.0=h02bd7ab_0
  - libgl=1.7.0=ha4b6fd6_2
  - fonts-conda-ecosystem=1=0
  - libstdcxx-ng=15.2.0=h4852527_7
  - pycparser=2.22=pyh29332c3_1
  - gettext=0.25.1=h3f43e3d_1
  - intel-gmmlib=22.8.2=hb700be7_0
  - msgpack-python=1.1.2=py311hdf67eae_1
  - icu=75.1=he02047a_0
  - mpg123=1.32.9=hc50e24c_0
  - python=3.11.14=hd63d673_2_cpython
  - attr=2.5.2=h39aace5_0
  - libcap=2.76=h0b2e76d_0
  - h2=4.3.0=pyhcf101f3_0
  - fribidi=1.0.16=hb03c661_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - libaec=1.1.4=h3f801dc_0
  - libcurl=8.18.0=h4e3cde8_0
  - libopenblas=0.3.30=pthreads_h94d23a6_3
  - libpciaccess=0.18=hb9d3cd8_0
  - svt-av1=3.1.2=hecca717_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - libpq=18.0=h3675c94_0
  - libhwloc=2.12.1=default_h7f8ec31_1002
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - ca-certificates=2026.1.4
  - platformdirs=4.5.0=pyhcf101f3_0
  - libiconv=1.18=h3b78370_2
  - python_abi=3.11=8_cp311
  - libev=4.33=hd590300_2
  - pooch=1.8.2=pyhd8ed1ab_3
  - libcups=2.3.3=hb8b1518_5
  - libopenvino-intel-npu-plugin=2025.2.0=hb617929_1
  - numpy=2.3.4=py311h2e04523_0
  - alsa-lib=1.2.14=hb9d3cd8_0
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - wayland-protocols=1.45=hd8ed1ab_0
  - cached_property=1.5.2=pyha770c72_1
  - gdk-pixbuf=2.44.4=h2b0a6b4_0
  - libgomp=15.2.0=h767d61c_7
  - xcb-util-keysyms=0.4.1=hb711507_0
  - librsvg=2.60.0=h61e6d4b_0
  - libstdcxx=15.2.0=h8f9b012_7
  - opencl-headers=2025.06.13=h5888daf_0
  - openjpeg=2.5.4=h55fea9a_0
  - lazy-loader=0.4=pyhd8ed1ab_2
  - brotli-python=1.2.0=py311h7c6b74e_0
  - libxcrypt=4.4.36=hd590300_1
  - matplotlib-base=3.10.7=py311h0f3be63_0
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - _libgcc_mutex=0.1=conda_forge
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - x264=1!164.3095=h166bdaf_2
  - openh264=2.6.0=hc22cd8d_0
  - libglib=2.86.1=h32235b2_2
  - x265=3.5=h924138e_3
  - scikit-learn=1.7.2=py311hc3e1efb_0
  - aom=3.9.1=hac33072_0
  - pyside6=6.9.3=py311he4c1a5a_1
  - joblib=1.5.2=pyhd8ed1ab_0
  - ncurses=6.5=h2d0b736_3
  - tbb=2022.3.0=h8d10470_1
  - keyutils=1.6.3=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - libopenvino-auto-batch-plugin=2025.2.0=hed573e4_1
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - pandas=2.3.3=py311hed34c8f_1
  - xorg-libx11=1.8.12=h4f16b4b_0
  - libffi=3.5.2=h9ec8514_0
  - xorg-libsm=1.2.6=he73a12e_0
  - libopenvino-intel-gpu-plugin=2025.2.0=hb617929_1
  - contourpy=1.3.3=py311hdf67eae_3
  - libopenvino-paddle-frontend=2025.2.0=h1862bb8_1
  - cached-property=1.5.2=hd8ed1ab_1
  - lcms2=2.17=h717163a_0
  - dav1d=1.2.1=hd590300_0
  - et_xmlfile=2.0.0=pyhd8ed1ab_1
  - pulseaudio-client=17.0=h9a8bead_2
  - readline=8.2=h8c095d6_2
  - libglx=1.7.0=ha4b6fd6_2
  - liblapack=3.9.0=38_h47877c9_openblas
  - libblas=3.9.0=38_h4a7cf45_openblas
  - packaging=25.0=pyh29332c3_1
  - cairo=1.18.4=h3394656_0
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libudev1=258.2=h07e904d_0
  - intel-media-driver=25.3.4=hecca717_0
  - libxcb=1.17.0=h8a09558_0
  - pytz=2025.2=pyhd8ed1ab_0
  - ld_impl_linux-64=2.44=h1aa0949_5
  - libfreetype=2.14.1=ha770c72_0
  - libopenvino=2025.2.0=hb617929_1
  - pip=25.3=pyh8b19718_0
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - libogg=1.3.5=hd0c01bc_1
  - liburing=2.12=hb700be7_0
  - libuuid=2.41.2=he9a06e4_0
  - gettext-tools=0.25.1=h3f43e3d_1
  - libopenvino-pytorch-frontend=2025.2.0=hecca717_1
  - matplotlib=3.10.7=py311h38be061_0
  - sdl2=2.32.56=h54a6638_0
  - brotli-bin=1.2.0=hf2c8021_0
  - standard-aifc=3.13.0=py311h38be061_3
  - hdf5=1.14.6=nompi_h1b119a7_104
  - libvorbis=1.3.7=h54a6638_2
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - tzdata=2025b=h78e105d_0
  - level-zero=1.26.0=hb700be7_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - fonts-conda-forge=1=hc364b38_1
  - qt6-main=6.9.3=h5c1c036_1
  - unicodedata2=17.0.0=py311h49ec1c0_0
  - libcblas=3.9.0=38_h0358290_openblas
  - wayland=1.24.0=hd6090a7_1
  - libasprintf-devel=0.25.1=h3f43e3d_1
  - libva=2.22.0=h4f16b4b_2
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - zstandard=0.25.0=py311haee01d2_1
  - spirv-tools=2025.4=hb700be7_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - glslang=16.0.0=hfd11570_0
  - libbrotlicommon=1.2.0=h09219d5_0
  - libgfortran5=15.2.0=hcd61629_7
  - ocl-icd=2.3.3=hb9d3cd8_0
  - libabseil=20250512.1=cxx17_hba17884_0
  - pysoundfile=0.13.1=pyhd8ed1ab_0
  - libopengl=1.7.0=ha4b6fd6_2
  - llvmlite=0.45.1=py311h41a00d4_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - xcb-util-image=0.4.0=hb711507_2
  - snappy=1.2.2=h03e3b7b_0
  - lazy_loader=0.4=pyhd8ed1ab_2
  - zipp=3.23.0=pyhd8ed1ab_0
  - c-ares=1.34.6=hb03c661_0
  - cffi=2.0.0=py311h03d9500_1
  - gmp=6.3.0=hac33072_2
  - standard-sunau=3.13.0=py311h38be061_3
  - libtiff=4.7.1=h9d88235_1
  - _openmp_mutex=4.5=2_gnu
  - liblzma=5.8.1=hb9d3cd8_2
  - tornado=6.5.2=py311h49ec1c0_2
  - idna=3.11=pyhd8ed1ab_0
  - libgcc=15.2.0=h767d61c_7
  - lerc=4.0.0=h0aef613_1
  - pysocks=1.7.1=pyha55dd90_7
  - libclang13=21.1.5=default_h746c552_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - bzip2=1.0.8=hda65f42_8
  - libopenvino-onnx-frontend=2025.2.0=h1862bb8_1
  - audioread=3.0.1=py311h38be061_3
  - libwebp-base=1.6.0=hd42ef1d_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - zlib-ng=2.2.5=hde8ca8f_0
  - pango=1.56.4=hadf4263_0
  - libopenvino-tensorflow-frontend=2025.2.0=h0767aad_1
  - libbrotlidec=1.2.0=hd53d788_0
  - qhull=2020.2=h434a139_5
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - xorg-libxscrnsaver=1.2.4=hb9d3cd8_0
  - libopenvino-tensorflow-lite-frontend=2025.2.0=hecca717_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - fonttools=4.60.1=py311h3778330_0
  - openpyxl=3.1.5=py311h534898f_2
  - pugixml=1.15=h3f63f65_0
  - ffmpeg=8.0.0=gpl_hbbdf940_906
  - libprotobuf=6.31.1=h49aed37_2
  - requests=2.32.5=pyhd8ed1ab_0
  - fontconfig=2.15.0=h7e30c49_1
  - six=1.17.0=pyhe01879c_1
  - libjpeg-turbo=3.1.2=hb03c661_0
  - libusb=1.0.29=h73b1eb8_0
  - libssh2=1.11.1=hcf80075_0
  - libfreetype6=2.14.1=h73754d4_0
  - pixman=0.46.4=h54a6638_1
  - xcb-util=0.4.1=h4f16b4b_2
  - libvpx=1.14.1=hac33072_0
  - libxkbcommon=1.13.0=hca5e8e5_0
  - certifi=2026.1.4
  - libsqlite=3.51.0=hee844dc_0
  - pcre2=10.46=h1321c63_0
  - libsndfile=1.2.2=hc60ed4a_1
  - libopenvino-ir-frontend=2025.2.0=hd41364c_1
  - libxml2=2.15.1=h26afc86_0
  - tk=8.6.13=noxft_hd72426e_102
  - libsystemd0=258.2=h07e904d_0
  - soxr=0.1.3=h0b41bf4_3
  - libopenvino-intel-cpu-plugin=2025.2.0=hb617929_1
  - krb5=1.21.3=h659f571_0
  - libgcc-ng=15.2.0=h69a702a_7
  - importlib-metadata=8.7.0=pyhe01879c_1
  - shaderc=2025.4=h3e344bc_0
  - libflac=1.4.3=h59595ed_0
  - libexpat=2.7.1=hecca717_0
  - sdl3=3.2.26=h68140b3_0
  - libasprintf=0.25.1=h3f43e3d_1
  - xcb-util-renderutil=0.3.10=hb711507_0
  - h5py=3.15.1=nompi_py311h0b2f468_101
  - libvulkan-loader=1.4.328.1=h5279c79_0
  - librosa=0.11.0=pyhd8ed1ab_0
  - libass=0.17.4=h96ad9f0_0
  - libxml2-16=2.15.1=ha9997c6_0
  - libgfortran=15.2.0=h69a702a_7
  - libopenvino-hetero-plugin=2025.2.0=hd41364c_1
  - graphite2=1.3.14=hecca717_2
  - brotli=1.2.0=h41a2e66_0
  - openssl=3.6.0=h26f9b46_0
  - pillow=12.0.0=py311h07c5bb8_0
  - libpng=1.6.50=h421ea60_1
  - openldap=2.6.10=he970967_0
  - cyrus-sasl=2.1.28=hd9c7081_0
  - zstd=1.5.7=hb8e6e7a_2
  - libzlib=1.3.1=hb9d3cd8_2
  - freetype=2.14.1=ha770c72_0
  - soxr-python=1.0.0=py311h1ddb823_1
  - kiwisolver=1.4.9=py311h724c32c_2
  - double-conversion=3.3.1=h5888daf_0
  - libegl=1.7.0=ha4b6fd6_2
  - dbus=1.16.2=h3c4dab8_0
  - ipykernel
  - ipywidgets
prefix: /home/songbird/miniconda3/envs/spectrace
