name: spectrace
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - numba
  - pyside6
  - pillow
  - h5py
  - librosa
  - audioread
  - pysoundfile
  - openpyxl
  - requests
  - setuptools
  - pip
  - ipykernel
  - ipywidgets